# Generated by Django 3.1 on 2020-12-11 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('problem', models.CharField(max_length=500)),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=1)),
                ('solution_a', models.CharField(max_length=500)),
                ('solution_b', models.CharField(max_length=500)),
                ('solution_c', models.CharField(max_length=500)),
                ('solution_d', models.CharField(max_length=500)),
                ('correct_solution', models.CharField(max_length=500)),
                ('solution_steps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.solution')),
            ],
        ),
    ]
