# Generated by Django 3.1.4 on 2020-12-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='correct_solution',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=1),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='problem',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='solution_a',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='solution_b',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='solution_c',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='solution_d',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
