# Generated by Django 3.1.4 on 2020-12-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_solvedexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='validated',
            field=models.BooleanField(default=True),
        ),
    ]
