# Generated by Django 3.1.4 on 2020-12-11 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('exercises', '0002_auto_20201211_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.subcategory'),
        ),
    ]
